alias flow='cd ~/Clients/Plumbing\ Flow/website/; op'
alias abp='cd ~/Clients/AB\ Plumbing/website; op'
alias aaap='cd ~/Clients/AAA\ Plumbing\ Services/website/; op'
alias ecc='cd ~/Clients/Executive\ Coffee/; o'
alias von='cd ~/Clients/Von\ Bravo/; o'
alias thouse='cd ~/Clients/Thai\ House/; o'