alias flow='cd ~/Clients/Plumbing\ Flow/website/; op'
alias abp='cd ~/Clients/AB\ Plumbing/website; op'
alias aaap='cd ~/Clients/AAA\ Plumbing\ Services/website/; op'
alias ecc='cd ~/Clients/Executive\ Coffee/website; op'
alias von='cd ~/Clients/Von\ Bravo/website/; op'
alias thouse='cd ~/Clients/Thai\ House/website/; op'